modLoader="javafml"
loaderVersion="[47,)"
license="ARR"

[[mods]]
modId="better_soul_stone"
version="1.0.0"
displayName="BetterSoulStone"
authors="Csdy"
description='''
'''

[[dependencies.better_soul_stone]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_soul_stone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_soul_stone]]
modId="curios"
mandatory=true
versionRange="[5.10.0,)"
ordering="NONE"
side="BOTH"