modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="better_soul_stone"
version="1.0.0"
displayName="BetterSoulStone"
authors="Mizi"
description='''
'''

[[dependencies.better_soul_stone]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_soul_stone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"